cursor #e1e3df
cursor_text_color #c0c9c0

foreground            #e1e3df
background            #111412
selection_foreground  #203529
selection_background  #b4ccbb
url_color             #97d4b0

color0   #111412
color1   #f3946d
color2   #6ad46c
color3   #fff172
color4   #83c9a0
color5   #2e6243
color6   #97d4b0
color7   #d1ded6
color8   #7f8983
color9   #ffbb9f
color10  #a5fea7
color11  #fff6a5
color12  #b0e9c7
color13  #cbffe0
color14  #ddffeb
color15  #f8fffb
