cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #442927
selection_background  #e7bdb9
url_color             #ffb3ae

color0   #131313
color1   #ff7372
color2   #9aff7f
color3   #ffe472
color4   #f29b95
color5   #763531
color6   #ffb3ae
color7   #fff0ef
color8   #a59a99
color9   #ffa09f
color10  #b8ffa5
color11  #ffeda5
color12  #ffbeba
color13  #ffc9c6
color14  #ffdcda
color15  #fff8f8
